name: Deploy Dashboard

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use the version of Node.js that your project requires

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Use the appropriate command for your project, if needed

    - name: Deploy to GitHub Pages
      env:
        API_KEY: ${{ secrets.GOOGLE_SHEETS_API_KEY }}
      run: |
        echo "API_KEY=${API_KEY}" > .env
        npm run deploy  # Ensure your project is configured to use the .env file if needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Adjust if your build output directory is different
